const bag = {
    id: productSelect.id,
    frete: etiquetaValor,
    vlrMerc: productSelect.price,
    pesoMerc: 1,
    nome: etiquetaNome,
    logradouro: etiquetaLogradouro,
    numero: etiquetaNumber,
    complemento: etiquetaComplement,
    bairro: etiquetaBairro,
    cep: etiquetaCep,
    cidade: etiquetaCidade,
    uf: etiquetaUf,
    contato: user.email ? user.email : etiquetaEmail,
    email: user.email ? user.email : etiquetaEmail,
    peso: 1,
    altura: 10,
    largura: 10,
    comprimento: 10,
    produto: productSelect.name,
    valor: productSelect.price,
    quantidade: 1,
    referencia: etiquetaReferencia,
}